[mgr]
ratio = [1, 2, 3]
sort_by = "alphabetical" 
linemode = "size"
show_symlink = true
sort_dir_first = true

[opener]
edit = [
	{ run = '$EDITOR "$@"', orphan = true, block = true, for = "unix" },
]
open = [
	{ run = '~/code_Master/scripts/launch.sh "$@"', orphan = true, desc = "Open" },
]
