[mgr]
ratio = [1, 2, 3]
sort_by = "alphabetical" 
linemode = "size"
show_symlink = true
sort_dir_first = true

[opener]
edit = [
	{ run = '$EDITOR "$@"', block = true},
]
open = [
	{ run = 'exec ~/code_Master/scripts/launch.sh "$@"', block = true, desc = "Open" },
]
play = [
	{ run = 'mpv "$@"', desc = "play media" },
]
