windowrule {
  name = opacity-95
  opacity = 0.95 override
  match:class = (jetbrains-idea|code-oss|discord|evince|jetbrains-studio|obsidian|vesktop)
}

windowrule {
  name = opacity-90
  opacity = 0.9 override 0.9 override
  match:class = (foobar2000.exe)
}

windowrule {
  name = float
  float = on
  match:class = (com.github.hluk.copyq|blueman-manager|pavucontrol|anki)
}

windowrule {
  name = force-tile-foobar2000
  tile = on
  match:initial_title = (foobar2000 v2.25)
}

windowrule {
  name = idle_inhibit_always
  idle_inhibit = always
  match:class = (foobar2000.exe|mpv|wihotspot|youtube-music|Spotify)
}

windowrule {
  name = idle_inhibit_lecture
  idle_inhibit = focus
  match:title = (Lecture)
}
