# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'catppuccin/tmux#v2.1.3'
# set -g @plugin 'binoymanoj/tmux-minimal-theme'
    
set -as terminal-features ",xterm-256color:RGB"

# Enable mouse control
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Vi mode
set-window-option -g mode-keys vi

# Vim-style copy mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R

# Open splits in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Status line
set -g status-bg black
set -g status-fg white

set -g allow-rename off
set -g automatic-rename on
set -g automatic-rename-format '#{pane_current_command}'
set -g focus-events on

set -g set-titles on
set -g set-titles-string '#T'

# history limit
set-option -g history-limit 100000

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
